name: 1per1
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * *'

  #workflow_dispatch:
jobs:
  Proses:
    runs-on: ubuntu-latest

    steps:
      - name: Check The Code
        uses: actions/checkout@v2
      - name: Get Files
        run: |
          curl -o vmess.txt -LJO "https://raw.githubusercontent.com/lagzian/SS-Collector/main/SS/VM_TrinityBase"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-telegram-bot==13.15
          
      - name: Run Python script
        run: |
          python satu-persatu.py


